# Generated by Django 2.2.12 on 2020-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
