# Generated by Django 2.2.12 on 2020-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_description_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
